language: python

python:
  - 3.6.4
env:
  - DJANGO=2.0.2
install:
  - pip install -r requirements.txt
before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - flake8
  - python manage.py test
